# Environment parameters

env: Hopper-v2
state_dim: 11
action_dim: 3
action_low: -1
action_high: 1
num_agents: 4
random_seed: 2019

# Training parameters

model: d3pg
batch_size: 256
num_steps_train: 500_000 # number of episodes from all agents
max_ep_length: 1000 # maximum number of steps per episode
replay_mem_size: 1_000_000 # maximum capacity of replay memory
discount_rate: 0.99 # Discount rate (gamma) for future rewards
n_step_returns: 1 # number of future steps to collect experiences for N-step returns
update_agent_ep: 1 # agent gets latest parameters from learner every update_agent_ep episodes
replay_queue_size: 1024 # queue with replays from all the agents
batch_queue_size: 64 # queue with batches given to learner
num_episode_save: 100
device: cuda
agent_device: cpu
save_reward_threshold: 1 # difference in best reward to save agent model

# Network parameters

critic_learning_rate: 0.0003
actor_learning_rate: 0.0003
dense_size: 256 # size of the 2 hidden layers in networks
tau: 0.005 # parameter for soft target network updates

# Miscellaneous

results_path: results

